CREATE TABLE users (
    id  SERIAL PRIMARY KEY NOT NULL,
    username    VARCHAR(20) NOT NULL,
    email   VARCHAR(50) NOT NULL, 
    password    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
